-- MySQL Script generated by MySQL Workbench
-- 12/15/17 11:02:16
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema inschrijfmodule
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema inschrijfmodule
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `inschrijfmodule` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `inschrijfmodule` ;

-- -----------------------------------------------------
-- Table `inschrijfmodule`.`rolnaam`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inschrijfmodule`.`rolnaam` ;

CREATE TABLE IF NOT EXISTS `inschrijfmodule`.`rolnaam` (
  `rolid` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `rolnaam` VARCHAR(255) NOT NULL COMMENT '',
  PRIMARY KEY (`rolid`)  COMMENT '')
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inschrijfmodule`.`account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inschrijfmodule`.`account` ;

CREATE TABLE IF NOT EXISTS `inschrijfmodule`.`account` (
  `account_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `gebruikersnaam` VARCHAR(255) NOT NULL COMMENT '',
  `wachtwoord` VARCHAR(255) NOT NULL COMMENT '',
  `rol_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`account_id`)  COMMENT '',
  CONSTRAINT `fk_Account_rolnaam1`
  FOREIGN KEY (`rol_id`)
  REFERENCES `inschrijfmodule`.`rolnaam` (`rolid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;

CREATE INDEX `fk_Account_rolnaam1_idx` ON `inschrijfmodule`.`account` (`rol_id` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `inschrijfmodule`.`soort`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inschrijfmodule`.`soort` ;

CREATE TABLE IF NOT EXISTS `inschrijfmodule`.`soort` (
  `soort_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `soort` VARCHAR(255) NOT NULL COMMENT '',
  `benodigdheid` VARCHAR(255) NOT NULL COMMENT '',
  `actief` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '',
  PRIMARY KEY (`soort_id`)  COMMENT '')
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inschrijfmodule`.`evenement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inschrijfmodule`.`evenement` ;

CREATE TABLE IF NOT EXISTS `inschrijfmodule`.`evenement` (
  `evenement_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `account_id` INT NOT NULL COMMENT '',
  `titel` VARCHAR(255) NOT NULL COMMENT '',
  `datum` DATETIME NOT NULL COMMENT '',
  `begintijd` DATETIME NOT NULL COMMENT '',
  `eindtijd` VARCHAR(255) NOT NULL COMMENT '',
  `onderwerp` VARCHAR(255) NOT NULL COMMENT '',
  `omschrijving` TEXT NULL COMMENT '',
  `vervoer` VARCHAR(255) NULL COMMENT '',
  `min_leerlingen` INT NULL COMMENT '',
  `max_leerlingen` INT NULL COMMENT '',
  `comment` VARCHAR(255) NULL COMMENT '',
  `locatie` VARCHAR(255) NOT NULL COMMENT '',
  `lokaalnummer` VARCHAR(255) NULL COMMENT '',
  `soort_id` INT NOT NULL COMMENT '',
  `contactnr` INT NULL COMMENT '',
  `status` TINYINT(1) NULL DEFAULT 1 COMMENT '',
  PRIMARY KEY (`evenement_id`, `soort_id`)  COMMENT '',
  CONSTRAINT `fk_evenement_account1`
  FOREIGN KEY (`account_id`)
  REFERENCES `inschrijfmodule`.`account` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evenement_soort1`
  FOREIGN KEY (`soort_id`)
  REFERENCES `inschrijfmodule`.`soort` (`soort_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB
  ROW_FORMAT = REDUNDANT;

CREATE INDEX `fk_evenement_account1_idx` ON `inschrijfmodule`.`evenement` (`account_id` ASC)  COMMENT '';

CREATE INDEX `fk_evenement_soort1_idx` ON `inschrijfmodule`.`evenement` (`soort_id` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `inschrijfmodule`.`leerling`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inschrijfmodule`.`leerling` ;

CREATE TABLE IF NOT EXISTS `inschrijfmodule`.`leerling` (
  `leerlingnummer` INT(11) NOT NULL COMMENT '',
  `account_id` INT(11) NOT NULL COMMENT '',
  `geslacht` VARCHAR(255) NULL COMMENT '',
  `roepnaam` VARCHAR(255) NOT NULL COMMENT '',
  `tussenvoegsel` VARCHAR(255) NULL COMMENT '',
  `achternaam` VARCHAR(255) NOT NULL COMMENT '',
  `opleiding` VARCHAR(255) NOT NULL COMMENT '',
  `geboortedatum` DATETIME NULL COMMENT '',
  `postcode` VARCHAR(255) NULL COMMENT '',
  `plaats` VARCHAR(255) NULL COMMENT '',
  `begindatum` DATETIME NOT NULL COMMENT '',
  `einddatum` DATETIME NULL COMMENT '',
  `plaatsing` TINYINT(1) NULL COMMENT '',
  `LWOO` TINYINT(1) NULL COMMENT '',
  `LGF` TINYINT(1) NULL COMMENT '',
  `groepscode` VARCHAR(255) NOT NULL COMMENT '',
  `deleted` TINYINT(1) NULL DEFAULT 0 COMMENT '',
  PRIMARY KEY (`leerlingnummer`)  COMMENT '',
  CONSTRAINT `fk_leerling_account1`
  FOREIGN KEY (`account_id`)
  REFERENCES `inschrijfmodule`.`account` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;

CREATE INDEX `fk_leerling_account1_idx` ON `inschrijfmodule`.`leerling` (`account_id` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `inschrijfmodule`.`inschrijving`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inschrijfmodule`.`inschrijving` ;

CREATE TABLE IF NOT EXISTS `inschrijfmodule`.`inschrijving` (
  `leerlingnummer` INT NOT NULL COMMENT '',
  `evenement_id` INT NOT NULL COMMENT '',
  `present` TINYINT(1) NULL COMMENT '',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `comment` VARCHAR(255) NULL COMMENT '',
  `toestemming` TINYINT(1) NOT NULL COMMENT '',
  `aangemeld_op` DATETIME NULL COMMENT '',
  `gewhitelist` TINYINT(1) NULL COMMENT '',
  `beoordeling` TINYINT NULL COMMENT '',
  PRIMARY KEY (`evenement_id`, `leerlingnummer`)  COMMENT '',
  CONSTRAINT `fk_inschrijving_evenement1`
  FOREIGN KEY (`evenement_id`)
  REFERENCES `inschrijfmodule`.`evenement` (`evenement_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inschrijving_leerling1`
  FOREIGN KEY (`leerlingnummer`)
  REFERENCES `inschrijfmodule`.`leerling` (`leerlingnummer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;

CREATE INDEX `fk_inschrijving_evenement1_idx` ON `inschrijfmodule`.`inschrijving` (`evenement_id` ASC)  COMMENT '';

CREATE INDEX `fk_inschrijving_leerling1_idx` ON `inschrijfmodule`.`inschrijving` (`leerlingnummer` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `inschrijfmodule`.`medewerker`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inschrijfmodule`.`medewerker` ;

CREATE TABLE IF NOT EXISTS `inschrijfmodule`.`medewerker` (
  `afkorting` VARCHAR(255) NOT NULL COMMENT '',
  `account_id` INT(11) NOT NULL COMMENT '',
  `roepnaam` VARCHAR(255) NOT NULL COMMENT '',
  `tussenvoegsel` VARCHAR(255) NULL COMMENT '',
  `achternaam` VARCHAR(255) NOT NULL COMMENT '',
  `functie` VARCHAR(255) NULL COMMENT '',
  `geslacht` VARCHAR(255) NOT NULL COMMENT '',
  `geboortedatum` DATETIME NOT NULL COMMENT '',
  `locatie` VARCHAR(255) NOT NULL COMMENT '',
  `telefoon` INT NOT NULL COMMENT '',
  `deleted` TINYINT(1) NULL DEFAULT 0 COMMENT '',
  PRIMARY KEY (`afkorting`)  COMMENT '',
  CONSTRAINT `fk_medewerker_account1`
  FOREIGN KEY (`account_id`)
  REFERENCES `inschrijfmodule`.`account` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;

CREATE INDEX `fk_medewerker_account1_idx` ON `inschrijfmodule`.`medewerker` (`account_id` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `inschrijfmodule`.`inventarisatie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inschrijfmodule`.`inventarisatie` ;

CREATE TABLE IF NOT EXISTS `inschrijfmodule`.`inventarisatie` (
  `invertarisatie_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `vakgebied` LONGTEXT NULL COMMENT '',
  `onderwerp` LONGTEXT NULL COMMENT '',
  `aantal_gastcolleges` MEDIUMTEXT NULL COMMENT '',
  `voorkeur_dag` MEDIUMTEXT NULL COMMENT '',
  `voorkeur_dagdeel` MEDIUMTEXT NULL COMMENT '',
  `hulpmiddel` MEDIUMTEXT NULL COMMENT '',
  `doelstelling` MEDIUMTEXT NULL COMMENT '',
  `verwachting` MEDIUMTEXT NULL COMMENT '',
  PRIMARY KEY (`invertarisatie_id`)  COMMENT '')
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inschrijfmodule`.`bedrijf`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inschrijfmodule`.`bedrijf` ;

CREATE TABLE IF NOT EXISTS `inschrijfmodule`.`bedrijf` (
  `bedrijf_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `inventarisatie_id` INT NOT NULL COMMENT '',
  `bedrijfsnaam` VARCHAR(255) NOT NULL COMMENT '',
  `branche` VARCHAR(255) NOT NULL COMMENT '',
  `webadres` VARCHAR(255) NULL COMMENT '',
  `adres` VARCHAR(255) NOT NULL COMMENT '',
  `postcode` VARCHAR(255) NOT NULL COMMENT '',
  `plaatsnaam` VARCHAR(255) NOT NULL COMMENT '',
  `contactnr` INT NOT NULL COMMENT '',
  `deleted` TINYINT(1) NULL COMMENT '',
  PRIMARY KEY (`bedrijf_id`)  COMMENT '',
  CONSTRAINT `fk_bedrijf_invertarisatie1`
  FOREIGN KEY (`inventarisatie_id`)
  REFERENCES `inschrijfmodule`.`inventarisatie` (`invertarisatie_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;

CREATE INDEX `fk_bedrijf_invertarisatie1_idx` ON `inschrijfmodule`.`bedrijf` (`inventarisatie_id` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `inschrijfmodule`.`contactpersoon`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inschrijfmodule`.`contactpersoon` ;

CREATE TABLE IF NOT EXISTS `inschrijfmodule`.`contactpersoon` (
  `contact_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `account_id` INT(11) NOT NULL COMMENT '',
  `bedrijf_id` INT NOT NULL COMMENT '',
  `roepnaam` VARCHAR(255) NOT NULL COMMENT '',
  `tussenvoegsel` VARCHAR(255) NULL COMMENT '',
  `achternaam` VARCHAR(255) NOT NULL COMMENT '',
  `functie` VARCHAR(255) NOT NULL COMMENT '',
  `telefoonnr.` VARCHAR(255) NOT NULL COMMENT '',
  `email-adres` VARCHAR(255) NOT NULL COMMENT '',
  `inventarisatie_id` INT NOT NULL COMMENT '',
  `deleted` TINYINT(1) NULL COMMENT '',
  PRIMARY KEY (`contact_id`)  COMMENT '',
  CONSTRAINT `fk_contactpersoon_bedrijf1`
  FOREIGN KEY (`bedrijf_id`)
  REFERENCES `inschrijfmodule`.`bedrijf` (`bedrijf_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contactpersoon_account1`
  FOREIGN KEY (`account_id`)
  REFERENCES `inschrijfmodule`.`account` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;

CREATE INDEX `fk_contactpersoon_bedrijf1_idx` ON `inschrijfmodule`.`contactpersoon` (`bedrijf_id` ASC)  COMMENT '';

CREATE INDEX `fk_contactpersoon_account1_idx` ON `inschrijfmodule`.`contactpersoon` (`account_id` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `inschrijfmodule`.`antwoord`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inschrijfmodule`.`antwoord` ;

CREATE TABLE IF NOT EXISTS `inschrijfmodule`.`antwoord` (
  `antwoord_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `antwoord` VARCHAR(255) NOT NULL COMMENT '',
  PRIMARY KEY (`antwoord_id`)  COMMENT '')
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inschrijfmodule`.`vragen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inschrijfmodule`.`vragen` ;

CREATE TABLE IF NOT EXISTS `inschrijfmodule`.`vragen` (
  `vraag_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `vraag` VARCHAR(255) NOT NULL COMMENT '',
  `antwoord_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`vraag_id`)  COMMENT '',
  CONSTRAINT `fk_vragen_antwoord1`
  FOREIGN KEY (`antwoord_id`)
  REFERENCES `inschrijfmodule`.`antwoord` (`antwoord_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;

CREATE INDEX `fk_vragen_antwoord1_idx` ON `inschrijfmodule`.`vragen` (`antwoord_id` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `inschrijfmodule`.`vragenlijst`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inschrijfmodule`.`vragenlijst` ;

CREATE TABLE IF NOT EXISTS `inschrijfmodule`.`vragenlijst` (
  `lijst` VARCHAR(255) NOT NULL COMMENT '',
  `soort_id` INT NOT NULL COMMENT '',
  `vraag_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`lijst`, `soort_id`)  COMMENT '',
  CONSTRAINT `fk_vragenlijst_vragen1`
  FOREIGN KEY (`vraag_id`)
  REFERENCES `inschrijfmodule`.`vragen` (`vraag_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vragenlijst_soort1`
  FOREIGN KEY (`soort_id`)
  REFERENCES `inschrijfmodule`.`soort` (`soort_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;

CREATE INDEX `fk_vragenlijst_vragen1_idx` ON `inschrijfmodule`.`vragenlijst` (`vraag_id` ASC)  COMMENT '';

CREATE INDEX `fk_vragenlijst_soort1_idx` ON `inschrijfmodule`.`vragenlijst` (`soort_id` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `inschrijfmodule`.`rechten`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inschrijfmodule`.`rechten` ;

CREATE TABLE IF NOT EXISTS `inschrijfmodule`.`rechten` (
  `rolnaam` VARCHAR(255) NOT NULL COMMENT '',
  `aanmaken_evenement` TINYINT(1) NOT NULL COMMENT '',
  `wijzigen_evenement` TINYINT(1) NOT NULL COMMENT '',
  `bekijken_evenement` TINYINT(1) NOT NULL COMMENT '',
  `bekijken_persoonsgegevens` TINYINT(1) NOT NULL COMMENT '',
  `wijzigen_persoonsgegevens` TINYINT(1) NOT NULL COMMENT '',
  `verwijderen_persoonsgegevens` TINYINT(1) NOT NULL COMMENT '',
  `inschrijven_leerling` TINYINT(1) NOT NULL COMMENT '',
  `goedkeuren_aanmelding` TINYINT(1) NOT NULL COMMENT '',
  `whitelisten_leerling` TINYINT(1) NOT NULL COMMENT '',
  `rolid` INT NOT NULL COMMENT '',
  PRIMARY KEY (`rolnaam`)  COMMENT '',
  CONSTRAINT `fk_rechten_rolnaam1`
  FOREIGN KEY (`rolid`)
  REFERENCES `inschrijfmodule`.`rolnaam` (`rolid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;

CREATE INDEX `fk_rechten_rolnaam1_idx` ON `inschrijfmodule`.`rechten` (`rolid` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `inschrijfmodule`.`foto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inschrijfmodule`.`foto` ;

CREATE TABLE IF NOT EXISTS `inschrijfmodule`.`foto` (
  `foto_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `fotonaam` VARCHAR(255) NOT NULL COMMENT '',
  `evenement_id` INT NOT NULL COMMENT '',
  `comment` VARCHAR(255) NULL COMMENT '',
  PRIMARY KEY (`foto_id`)  COMMENT '',
  CONSTRAINT `fk_foto_evenement1`
  FOREIGN KEY (`evenement_id`)
  REFERENCES `inschrijfmodule`.`evenement` (`evenement_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;

CREATE INDEX `fk_foto_evenement1_idx` ON `inschrijfmodule`.`foto` (`evenement_id` ASC)  COMMENT '';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
